/* =====================================================
   mejob — data.js
   Static mock data: jobs, categories, freelancers, news
   ===================================================== */

const DATA = {

  popularTags: [
    'นักพัฒนาซอฟต์แวร์', 'UX Designer', 'Digital Marketing',
    'บัญชี', 'HR', 'Data Analyst', 'งาน Remote'
  ],

  categories: [
    { icon: '💻', name: 'IT & Software', count: '12,450', color: '#38bdf8' },
    { icon: '🎨', name: 'ดีไซน์ & ครีเอทีฟ', count: '4,820', color: '#a855f7' },
    { icon: '📊', name: 'บัญชี & การเงิน', count: '6,310', color: '#22c55e' },
    { icon: '📣', name: 'การตลาด', count: '5,190', color: '#f97316' },
    { icon: '🏗️', name: 'วิศวกรรม', count: '3,760', color: '#fbbf24' },
    { icon: '🏥', name: 'สาธารณสุข', count: '2,890', color: '#ef4444' },
    { icon: '🎓', name: 'การศึกษา', count: '2,140', color: '#06b6d4' },
    { icon: '⚖️', name: 'กฎหมาย', count: '1,430', color: '#84cc16' },
    { icon: '🚗', name: 'โลจิสติกส์', count: '3,580', color: '#f59e0b' },
    { icon: '🍽️', name: 'อาหาร & บริการ', count: '4,210', color: '#ec4899' },
    { icon: '🏠', name: 'อสังหาริมทรัพย์', count: '1,870', color: '#10b981' },
    { icon: '📱', name: 'E-Commerce', count: '7,650', color: '#6366f1' },
  ],

  jobs: [
    {
      id: 1,
      title: 'Senior React Developer',
      company: 'TechStart Thailand',
      logo: '🏢',
      logoBg: 'rgba(56,189,248,0.15)',
      type: 'Remote',
      location: 'กรุงเทพฯ',
      salary: '80,000 – 120,000',
      tags: ['React', 'TypeScript', 'Node.js'],
      posted: '2 ชั่วโมงที่แล้ว',
      filter: 'remote',
      badge: 'hot',
    },
    {
      id: 2,
      title: 'UX/UI Designer',
      company: 'Creative Lab Co.',
      logo: '🎨',
      logoBg: 'rgba(168,85,247,0.15)',
      type: 'งานประจำ',
      location: 'กรุงเทพฯ',
      salary: '45,000 – 70,000',
      tags: ['Figma', 'User Research', 'Prototyping'],
      posted: '5 ชั่วโมงที่แล้ว',
      filter: 'fulltime',
      badge: 'new',
    },
    {
      id: 3,
      title: 'Digital Marketing Manager',
      company: 'BrandBoost Asia',
      logo: '📣',
      logoBg: 'rgba(249,115,22,0.15)',
      type: 'งานประจำ',
      location: 'นนทบุรี',
      salary: '55,000 – 80,000',
      tags: ['SEO', 'Google Ads', 'Analytics'],
      posted: '1 วันที่แล้ว',
      filter: 'fulltime',
      badge: null,
    },
    {
      id: 4,
      title: 'Data Analyst',
      company: 'DataVision Inc.',
      logo: '📊',
      logoBg: 'rgba(34,197,94,0.15)',
      type: 'Hybrid',
      location: 'เชียงใหม่',
      salary: '40,000 – 65,000',
      tags: ['Python', 'SQL', 'Power BI'],
      posted: '2 วันที่แล้ว',
      filter: 'fulltime',
      badge: 'new',
    },
    {
      id: 5,
      title: 'Mobile Developer (Flutter)',
      company: 'AppWave Studio',
      logo: '📱',
      logoBg: 'rgba(99,102,241,0.15)',
      type: 'Remote',
      location: 'ทั่วประเทศ',
      salary: '60,000 – 95,000',
      tags: ['Flutter', 'Dart', 'Firebase'],
      posted: '3 วันที่แล้ว',
      filter: 'remote',
      badge: 'hot',
    },
    {
      id: 6,
      title: 'HR Business Partner',
      company: 'MegaCorp Thailand',
      logo: '👥',
      logoBg: 'rgba(251,191,36,0.15)',
      type: 'งานประจำ',
      location: 'กรุงเทพฯ',
      salary: '50,000 – 75,000',
      tags: ['HRBP', 'Recruitment', 'Labor Law'],
      posted: '4 วันที่แล้ว',
      filter: 'fulltime',
      badge: null,
    },
    {
      id: 7,
      title: 'Content Creator (Part-time)',
      company: 'SocialBuzz Media',
      logo: '🎬',
      logoBg: 'rgba(236,72,153,0.15)',
      type: 'พาร์ทไทม์',
      location: 'Online',
      salary: '15,000 – 25,000',
      tags: ['TikTok', 'Instagram', 'Video Edit'],
      posted: '5 วันที่แล้ว',
      filter: 'parttime',
      badge: null,
    },
    {
      id: 8,
      title: 'Full Stack Engineer',
      company: 'FinNext Solutions',
      logo: '⚙️',
      logoBg: 'rgba(16,185,129,0.15)',
      type: 'Remote',
      location: 'กรุงเทพฯ',
      salary: '90,000 – 150,000',
      tags: ['Go', 'Vue.js', 'PostgreSQL'],
      posted: '6 วันที่แล้ว',
      filter: 'remote',
      badge: 'hot',
    },
    {
      id: 9,
      title: 'นักบัญชีอาวุโส',
      company: 'Accountancy Plus',
      logo: '💰',
      logoBg: 'rgba(34,197,94,0.12)',
      type: 'งานประจำ',
      location: 'กรุงเทพฯ',
      salary: '40,000 – 55,000',
      tags: ['SAP', 'Financial Report', 'CPA'],
      posted: '1 สัปดาห์ที่แล้ว',
      filter: 'fulltime',
      badge: null,
    },
    {
      id: 10,
      title: 'Freelance Copywriter',
      company: 'อิสระ',
      logo: '✍️',
      logoBg: 'rgba(249,115,22,0.12)',
      type: 'ฟรีแลนซ์',
      location: 'Online',
      salary: '500 – 2,000/ชิ้น',
      tags: ['Copywriting', 'SEO Content', 'Thai/ENG'],
      posted: '1 สัปดาห์ที่แล้ว',
      filter: 'freelance',
      badge: null,
    },
    {
      id: 11,
      title: 'Product Manager',
      company: 'GrowthHQ',
      logo: '🚀',
      logoBg: 'rgba(56,189,248,0.12)',
      type: 'Hybrid',
      location: 'กรุงเทพฯ',
      salary: '100,000 – 160,000',
      tags: ['Product Strategy', 'Agile', 'OKR'],
      posted: '2 สัปดาห์ที่แล้ว',
      filter: 'fulltime',
      badge: null,
    },
    {
      id: 12,
      title: 'Barista Part-time (Weekend)',
      company: 'Café Aroma',
      logo: '☕',
      logoBg: 'rgba(180,83,9,0.15)',
      type: 'พาร์ทไทม์',
      location: 'เชียงใหม่',
      salary: '400/วัน',
      tags: ['บาริสต้า', 'ลูกค้าสัมพันธ์'],
      posted: '3 วันที่แล้ว',
      filter: 'parttime',
      badge: 'new',
    },
  ],

  hireFeatures: [
    'เข้าถึงผู้หางานคุณภาพกว่า 1.2 ล้านโปรไฟล์',
    'ระบบ AI กรองผู้สมัครที่เหมาะสมอัตโนมัติ',
    'จัดการประกาศงานได้ง่ายบน Dashboard',
    'รับ Resume และ Portfolio พร้อมกัน',
    'ประกาศงานฟรี ไม่มีค่าใช้จ่ายแอบแฝง',
  ],

  applicantColors: ['#f97316','#38bdf8','#a855f7','#22c55e','#fbbf24'],

  freelancers: [
    {
      emoji: '🧑‍💻',
      avatarBg: 'rgba(56,189,248,0.15)',
      name: 'ชลธิชา ว.',
      skill: 'Full Stack Developer',
      title: 'รับพัฒนาเว็บ React / Next.js ระบบ E-Commerce ครบวงจร',
      rate: '฿1,500/ชั่วโมง',
      rating: '4.9',
      reviews: 84,
    },
    {
      emoji: '🎨',
      avatarBg: 'rgba(168,85,247,0.15)',
      name: 'ปิยะ ส.',
      skill: 'UI/UX Designer',
      title: 'ออกแบบ UI/UX สวย ใช้งานง่าย พร้อม Prototype ครบ',
      rate: '฿1,200/ชั่วโมง',
      rating: '4.8',
      reviews: 62,
    },
    {
      emoji: '📸',
      avatarBg: 'rgba(249,115,22,0.15)',
      name: 'มนัสนันท์ พ.',
      skill: 'Photographer & Video',
      title: 'ถ่ายภาพ Product / Lookbook / รับตัดต่อวิดีโอมืออาชีพ',
      rate: '฿3,500/วัน',
      rating: '5.0',
      reviews: 47,
    },
    {
      emoji: '✍️',
      avatarBg: 'rgba(34,197,94,0.15)',
      name: 'ธนิตา ล.',
      skill: 'Content & Copywriter',
      title: 'เขียน Content SEO ไทย-อังกฤษ บทความ Blog Advertorial',
      rate: '฿800/ชิ้น',
      rating: '4.7',
      reviews: 130,
    },
    {
      emoji: '📊',
      avatarBg: 'rgba(251,191,36,0.15)',
      name: 'กรกฎ อ.',
      skill: 'Data Analyst',
      title: 'วิเคราะห์ข้อมูล สร้าง Dashboard Power BI / Looker Studio',
      rate: '฿1,800/ชั่วโมง',
      rating: '4.9',
      reviews: 38,
    },
    {
      emoji: '🎬',
      avatarBg: 'rgba(236,72,153,0.15)',
      name: 'ภัทรพล จ.',
      skill: 'Motion Designer',
      title: 'ทำ Motion Graphic / Explainer Video / Social Media Ads',
      rate: '฿5,000/ชิ้น',
      rating: '4.8',
      reviews: 55,
    },
  ],

  news: [
    {
      emoji: '🤖',
      emojiColor: '#38bdf8',
      tag: 'เทคโนโลยี',
      tagColor: 'rgba(56,189,248,0.12)',
      tagTextColor: '#38bdf8',
      title: 'AI เปลี่ยนโลกการทำงาน: 5 ทักษะที่คนรุ่นใหม่ต้องมีปี 2025',
      date: '24 พ.ค. 2025',
      readTime: '5 นาที',
    },
    {
      emoji: '💼',
      emojiColor: '#f97316',
      tag: 'ตลาดแรงงาน',
      tagColor: 'rgba(249,115,22,0.12)',
      tagTextColor: '#f97316',
      title: 'เงินเดือน Developer ไทย 2025 ขึ้น 18% เฉลี่ยสูงสุดในอาเซียน',
      date: '22 พ.ค. 2025',
      readTime: '4 นาที',
    },
    {
      emoji: '🏠',
      emojiColor: '#22c55e',
      tag: 'Remote Work',
      tagColor: 'rgba(34,197,94,0.12)',
      tagTextColor: '#22c55e',
      title: 'Work from Anywhere: บริษัทไทยกว่า 60% เปิด Hybrid Work ถาวร',
      date: '20 พ.ค. 2025',
      readTime: '3 นาที',
    },
    {
      emoji: '🎓',
      emojiColor: '#a855f7',
      tag: 'พัฒนาตัวเอง',
      tagColor: 'rgba(168,85,247,0.12)',
      tagTextColor: '#a855f7',
      title: '10 คอร์สออนไลน์ฟรีที่ช่วยเพิ่มเงินเดือนคุณได้ในปีนี้',
      date: '18 พ.ค. 2025',
      readTime: '6 นาที',
    },
    {
      emoji: '📈',
      emojiColor: '#fbbf24',
      tag: 'เศรษฐกิจ',
      tagColor: 'rgba(251,191,36,0.12)',
      tagTextColor: '#fbbf24',
      title: 'Startup ไทยระดม VC กว่า 2 พันล้าน เปิดรับสมัครพนักงานพุ่ง',
      date: '15 พ.ค. 2025',
      readTime: '4 นาที',
    },
    {
      emoji: '⚖️',
      emojiColor: '#ef4444',
      tag: 'กฎหมายแรงงาน',
      tagColor: 'rgba(239,68,68,0.12)',
      tagTextColor: '#ef4444',
      title: 'แรงงานไทยต้องรู้! สิทธิ์ใหม่ตาม พ.ร.บ. คุ้มครองแรงงาน 2025',
      date: '12 พ.ค. 2025',
      readTime: '7 นาที',
    },
  ],

  socialLinks: [
    { icon: 'f', label: 'Facebook', color: '#1877f2' },
    { icon: 'in', label: 'LinkedIn', color: '#0a66c2' },
    { icon: 'X', label: 'X / Twitter', color: '#fff' },
    { icon: '▶', label: 'YouTube', color: '#ff0000' },
    { icon: '◎', label: 'TikTok', color: '#fff' },
  ],

  footerLinks: [
    {
      title: 'สำหรับผู้หางาน',
      links: ['ค้นหางาน', 'งาน Remote', 'งานพาร์ทไทม์', 'ฟรีแลนซ์', 'เงินเดือน'],
    },
    {
      title: 'สำหรับนายจ้าง',
      links: ['ลงประกาศงาน', 'หาฟรีแลนซ์', 'แพ็กเกจ Premium', 'Employer Branding'],
    },
    {
      title: 'ข่าวสาร',
      links: ['บทความอาชีพ', 'เทรนด์งาน', 'เงินเดือน', 'สัมภาษณ์งาน', 'พัฒนาตัวเอง'],
    },
    {
      title: 'เกี่ยวกับเรา',
      links: ['เกี่ยวกับ mejob', 'ร่วมงานกับเรา', 'ติดต่อเรา', 'นักลงทุน', 'Blog'],
    },
  ],
};
